format = '''
$username$hostname$shlvl$kubernetes$directory$custom$git_branch$git_commit$git_state$git_status$hg_branch$docker_context$package$terraform$vagrant$conda$env_var$cmd_duration$jobs$battery$status$shell$character
'''
add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[git_branch]
symbol = ' '

[directory]
read_only = ' '
disabled = false

[package]
symbol = ' '

[custom.virtual_env]
command = 'basename $VIRTUAL_ENV'
symbol = ' '
style = 'white dimmed'
format = '[\($symbol($output)\)]($style) '
when = '! test -z $VIRTUAL_ENV'
